# Generated by Django 3.0.3 on 2021-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(blank=True, max_length=200)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('size', models.CharField(blank=True, choices=[('L', 'Ladies'), ('M', 'Men'), ('J', 'Junior')], max_length=1)),
                ('grip', models.CharField(blank=True, choices=[('LH', 'Left Hand'), ('RH', 'Right Hand')], max_length=2)),
                ('clubType', models.CharField(blank=True, choices=[('DR', 'Driver'), ('Woods', (('3w', '3 wood'), ('2w', '2 wood'), ('1w', '1 wood'))), ('Iron', (('3i', '3 iron'), ('4i', '4 iron'), ('5i', '5 iron'), ('6i', '6 iron'), ('7i', '7 iron'), ('8i', '8 iron'))), ('W', 'Wedge'), ('P', 'Putter')], max_length=2)),
            ],
        ),
    ]
