# Generated by Django 3.0.3 on 2021-10-29 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_image', models.ImageField(upload_to='images/')),
                ('club_name', models.CharField(max_length=50, verbose_name='Club name')),
                ('club_brand', models.CharField(blank=True, choices=[('WIL', 'Wilson'), ('PK', 'Pike'), ('FZ', 'Frazer')], max_length=20)),
                ('club_type', models.CharField(blank=True, choices=[('OTHER', (('DR', 'Driver'), ('W', 'Wedge'), ('P', 'Putter'))), ('IRON', (('3i', '3 iron'), ('4i', '4 iron'), ('5i', '5 iron'), ('6i', '6 iron'), ('7i', '7 iron'), ('8i', '8 iron'))), ('WOOD', (('3w', '3 wood'), ('2w', '2 wood'), ('1w', '1 wood')))], max_length=20)),
                ('club_summary', models.CharField(max_length=200, verbose_name='Club summary')),
                ('club_size', models.CharField(blank=True, choices=[('SM', 'Short'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('club_gripDirection', models.CharField(blank=True, choices=[('LH', 'Left hand'), ('RH', 'Right hand')], max_length=10)),
                ('club_gender', models.CharField(blank=True, choices=[('L', 'Ladies'), ('M', 'Mens'), ('J', 'Juniors')], max_length=10)),
                ('club_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club_set', models.CharField(blank=True, choices=[('F', 'Full'), ('H', 'Half')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderStatus', models.CharField(default='Unpaid', max_length=10)),
                ('club_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Club')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='bookFittingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fittingDate', models.DateTimeField(auto_now_add=True)),
                ('fittingStatus', models.CharField(default='Pending', max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Club')),
            ],
        ),
    ]
