# Generated by Django 3.0.3 on 2021-11-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookfitting',
            old_name='clubDetails',
            new_name='club_details',
        ),
        migrations.RenameField(
            model_name='bookfitting',
            old_name='clubName',
            new_name='club_name',
        ),
        migrations.RenameField(
            model_name='bookfitting',
            old_name='contactDetails',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='bookfitting',
            old_name='fittingDate',
            new_name='fitting_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='generalenquiry',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
