# Generated by Django 3.0.3 on 2021-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='dateOfOrder',
            field=models.DateField(auto_now=True),
        ),
    ]
