# Generated by Django 3.0.3 on 2021-10-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderStatus', models.CharField(default='Unpaid', max_length=10)),
                ('club_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Club')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Customer')),
                ('set_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Club_set')),
            ],
        ),
        migrations.CreateModel(
            name='bookFittingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fittingDate', models.DateTimeField(auto_now_add=True)),
                ('fittingStatus', models.CharField(default='Pending', max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Club')),
            ],
        ),
    ]
