# Generated by Django 3.0.3 on 2021-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(blank=True, choices=[('WIL', 'Wilson'), ('PK', 'Pike'), ('FZ', 'Frazer')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('A', 'Accessory'), ('C', 'Club'), ('F', 'FullSet'), ('H', 'HalfSet')], max_length=20)),
                ('type', models.CharField(blank=True, choices=[('OTHER', (('DR', 'Driver'), ('W', 'Wedge'), ('P', 'Putter'), ('F', 'Fairway'))), ('IRON', (('3i', '3 iron'), ('4i', '4 iron'), ('5i', '5 iron'), ('6i', '6 iron'), ('7i', '7 iron'), ('8i', '8 iron')))], max_length=20)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, choices=[('SM', 'Short'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('gripDirection', models.CharField(blank=True, choices=[('LH', 'Left hand'), ('RH', 'Right hand')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Ladies'), ('M', 'Mens'), ('J', 'Juniors')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stockCondition', models.CharField(choices=[('OOS', 'Out of stock'), ('IS', 'In stock')], default='IS', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='SetOfClubs',
        ),
    ]
