# Generated by Django 3.0.3 on 2021-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0002_auto_20211122_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Accessory'), ('C', 'Club'), ('S', 'SetOfClubs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('OTHER', (('F', 'FullSet'), ('H', 'HalfSet'), ('DR', 'Driver'), ('W', 'Wedge'), ('P', 'Putter'), ('F', 'Fairway'))), ('IRON', (('3i', '3 iron'), ('4i', '4 iron'), ('5i', '5 iron'), ('6i', '6 iron'), ('7i', '7 iron'), ('8i', '8 iron')))], max_length=20),
        ),
    ]
