# Generated by Django 3.0.3 on 2021-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0002_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='club_stockCondition',
            field=models.CharField(choices=[('OOS', 'Out of stock'), ('IS', 'In stock')], default='IS', max_length=10),
        ),
    ]
