# Generated by Django 3.0.3 on 2021-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0002_auto_20211112_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfitting',
            name='club_details',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='bookfitting',
            name='club_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookfitting',
            name='customer_ID',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookfitting',
            name='fitting_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookfitting',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Lady'), ('M', 'Male'), ('J', 'Juniors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='generalenquiry',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='generalenquiry',
            name='enquiry',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generalenquiry',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='generalenquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
