# Generated by Django 3.0.3 on 2021-12-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0003_auto_20211212_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='productID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
