# Generated by Django 3.0.3 on 2021-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0003_auto_20211105_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_set',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('F', 'Full'), ('H', 'Half')], max_length=10),
        ),
    ]
