# Generated by Django 3.0.3 on 2021-11-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0004_auto_20211123_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderStatus', models.CharField(default='Unpaid', max_length=10)),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Customer')),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Product')),
            ],
        ),
    ]
