# Generated by Django 3.0.3 on 2021-11-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0005_orderform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='productID',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='generalenquiry',
            name='enquiry',
            field=models.TextField(max_length=300),
        ),
    ]
