# Generated by Django 3.0.3 on 2021-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0006_auto_20211130_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfitting',
            name='fitting_date',
            field=models.DateField(max_length=30),
        ),
    ]
