# Generated by Django 3.0.3 on 2021-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0007_auto_20211130_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalenquiry',
            name='email',
        ),
        migrations.AddField(
            model_name='generalenquiry',
            name='from_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
