# Generated by Django 3.0.3 on 2021-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0009_auto_20211205_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Lady'), ('G', 'Gent'), ('J', 'Junior')], max_length=10),
        ),
    ]
