# Generated by Django 3.0.3 on 2021-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0010_auto_20211205_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
