# Generated by Django 3.0.3 on 2021-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0011_auto_20211205_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalenquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
