# Generated by Django 3.0.3 on 2021-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0012_generalenquiry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
