# Generated by Django 3.0.3 on 2021-12-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0014_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfshop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookfitting',
            name='fitting_date',
            field=models.DateField(max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderForm',
        ),
    ]
