# Generated by Django 3.0.3 on 2021-12-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfshop', '0014_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
